### ISSUE TITLE
What happened to OAML?

### ISSUE THREAD

**Issue by robme-l** [openml-labs/gama#209]
I came across [this](https://doi.org/10.1007/s10994-022-06262-0) paper that proposed Online AutoML with a link to this repo, however it seems that the online framework it mentioned is not here. What happened to it?

**Comment by PGijsbers** [comment]
It is my understanding that it currently lives on the [`oaml`](https://github.com/openml-labs/gama/tree/oaml) branch. @Bilgecelik please chime in if that is not the latest version.

**Comment by robme-l** [comment]
@PGijsbers you are right I checked it out. It didn't have the exact requirements I was looking for but it seems that most of it besides the Genetic programming can be easily recreated using the existing River library. It's a shame however that it's not even mentioned in GAMA's docs or actively supported however because it seemed like it would show promise. Closing this issue here.
